config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :teachers
  resources :students

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mastery_level.rb
class MasteryLevel < ApplicationRecord
  belongs_to :students, through :standard
  belongs_to :standard
end

app/models/standard.rb
class Standard < ApplicationRecord
  belongs to :students
  belongs to :teachers
  has_many :mastery_levels 
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :teacher
  has_many :mastery_level, through: :standard
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_and_belongs_to_many :students
  has_many :standards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def create 
    @teacher = Teacher.find(params[:teacher_id])
    @student = @teacher.students.find(params[:id])
    redirect_to teacher_path(@teacher)
  end

  def destroy
    @teacher = Teacher.find(params[:teacher_id])
    @student = @teacher.students.find(params[:id])
    @student.destroy
    redirect_to teacher_path(@teacher)

  private
    def student_params
      params.require(:student).permit(:first_name, :last_name)
    end
end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teacher = Teacher.find(params[:id])
  end

  def show 
    @teacher = Teacher.find(params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def create 
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to @teacher
    else
      render 'new'
    end
  end

  private
    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name, :email, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  http_basic_authenticate_with name: "Teacher1", password: "secret",
except: [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GradeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= form_with(model: [ @teacher, @teacher.students.build ], local: true) do |form| %>

<% if @student.errors.any? %>
  <div id="error_explanation">
    <h2>
      <% pluralize(@student.errors.count, "error") %> prohibited
      this student from being saved: 
    </h2>
    <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= form.label :first_name %><br>
  <%= form.text_field :first_name %>
</p>

<p>
  <%= form.label :last_name %><br>
  <%= form.text_field :last_name %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

app/views/students/show.html.erb
<h1>You've successfully added a new student!</h1>
<p>
  <strong>First Name:</strong>
  <%= @student.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @student.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @student.password %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %>
<%= link_to 'Add Another Student', new_student_path(@student) %>

app/views/teachers/edit.html.erb
<h1>Edit Your Account Information</h1>
<%= form_with model: @teacher, local: true do |form| %>

<% if @teacher.errors.any? %>
  <div id="error_explanation">
    <h2>
      <% pluralize(@teacher.errors.count, "error") %> prohibited
      this teacher from being saved: 
    </h2>
    <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= form.label :first_name %><br>
  <%= form.text_field :first_name %>
</p>

<p>
  <%= form.label :last_name %><br>
  <%= form.text_field :last_name %>
</p>

<p>
  <%= form.label :email %><br>
  <%= form.text_field :email %>
</p>

<p>
  <%= form.label :password %><br>
  <%= form.text_field :password %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

<%= link_to 'Home', teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= form_with model: @teacher, local: true do |form| %>

<% if @teacher.errors.any? %>
  <div id="error_explanation">
    <h2>
      <% pluralize(@teacher.errors.count, "error") %> prohibited
      this teacher from being saved: 
    </h2>
    <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= form.label :first_name %><br>
  <%= form.text_field :first_name %>
</p>

<p>
  <%= form.label :last_name %><br>
  <%= form.text_field :last_name %>
</p>

<p>
  <%= form.label :email %><br>
  <%= form.text_field :email %>
</p>

<p>
  <%= form.label :password %><br>
  <%= form.text_field :password %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

app/views/teachers/show.html.erb
<h1>Welcome to MasteryTracker <%= @teacher.first_name %></h1>

<%= link_to 'Edit Your Account', edit_teacher_path(@teacher) %>

<h2>Your Student Roster:</h2>
  <%= render @teacher.students %>

<h2>Add A Student</h2>
<%= render 'students/new' %>

app/views/welcome/index.html.erb
<h1>Welcome To Your Grading Tracker</h1>
  <p>You can add students, standards and update mastery levels in a color-coded, efficient manner!</p>
<%= link_to 'Sign Up', new_teacher_path %>
<%= link_to 'Login', controller: 'welcome' %>